# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Unicode-LineBreak
version:      1.011
version_from: lib/Unicode/LineBreak.pm
installdirs:  site
requires:
    Encode:                        1.98
    MIME::Charset:                 1.006.2
    Test::More:                    0.45

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
